name: check cpp documentation

on:
  push:
    branches: [ "main"]

permissions:
  contents: read

jobs:
 build:
  runs-on: ubuntu-latest
    
  steps:
    - uses: actions/checkout@v3
    - name: install Cmake
      run: sudo apt-get install cmake 
    - name: install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
    - name: build 
      run: |
        ls
        mkdir build 
        cd build
        cmake build .. -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
        cd ..
        cmake --build build
        ls
    - name: run test
      run: |
        build/testDocumentation
